# Generated by Django 5.2.3 on 2025-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_place_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='culture_variety_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_variety_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_variety_description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='temperature',
            field=models.CharField(blank=True, choices=[], max_length=64, null=True),
        ),
    ]
