# Generated by Django 5.2.3 on 2025-06-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_userprofile_city_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='title_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='title_ky',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='culturevariety',
            name='culture_variety_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='culturevariety',
            name='culture_variety_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='address_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='address_ky',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='event_type_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='event_type_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_ky',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hotelhygiene',
            name='hygiene_title_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotelhygiene',
            name='hygiene_title_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mealtime',
            name='meal_time_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mealtime',
            name='meal_time_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mealtype',
            name='meal_type_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mealtype',
            name='meal_type_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_name_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='region_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regionmeal',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionmeal',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='regionmeal',
            name='meal_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='regionmeal',
            name='meal_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_en',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_ky',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='specializedmenu',
            name='specialized_menu_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='specializedmenu',
            name='specialized_menu_ky',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
