# Generated by Django 5.2.3 on 2025-06-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_culture_culture_variety_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='temperature',
            field=models.PositiveSmallIntegerField(blank=True, choices=[], null=True),
        ),
    ]
