# Generated by Django 5.2.3 on 2025-06-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_attraction_description_en_attraction_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='bikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='cars',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pets',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
