# Generated by Django 5.2.3 on 2025-06-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_place_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=1, upload_to='event_image/'),
            preserve_default=False,
        ),
    ]
