# Generated by Django 5.2.3 on 2025-06-22 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_alter_hotel_bathrooms_alter_hotel_bedrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrestaurantlike',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.reviewrestaurant'),
        ),
    ]
