# Generated by Django 5.2.3 on 2025-06-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_reviewrestaurantlike_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewattractionlike',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.reviewattraction'),
        ),
    ]
