# Generated by Django 5.2.3 on 2025-06-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='culture_variety_description',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='culture_variety_description_en',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='culture_variety_description_ky',
        ),
    ]
