# Generated by Django 5.2.3 on 2025-06-22 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_reviewattractionlike_attraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritehotel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='favoriteplace',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FavoriteAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.attraction')),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.favorite')),
            ],
            options={
                'unique_together': {('attraction', 'favorite')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.favorite')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'favorite')},
            },
        ),
    ]
