# Generated by Django 5.2.3 on 2025-06-26 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_alter_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractreview',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='review_photos/'),
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='service_score',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='abstractreview',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewattraction',
            name='attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel.attraction'),
        ),
    ]
